server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saferoute
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

tmap:
  app-key: ${TMAP_APP_KEY}

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
